name: Repo Setup
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  setup:
    if: "${{ (github.event_name == 'push' && contains(github.event.commits[0].message, 'Initial commit')) || github.event_name == 'workflow_dispatch' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Create branch protections
        uses: ndcmsl/repo-setup-action@main
        id: create_branch_protections
        with:
          token: ${{ secrets.token }}
          repo: ${{ github.repository }}
          owner: ${{ github.repository_owner }}
