name: Dev Unit Test, Build image & Push

on:
  workflow_call:
    secrets:
      token:
        required: true
      docker_username:
        required: true
      docker_password:
        required: true

env: 
  GH_TOKEN: ${{ secrets.token }}
  NPM_TOKEN: ${{ secrets.token }}
  NODE_AUTH_TOKEN: ${{ secrets.token }}
  DOCKER_USERNAME: ${{ secrets.docker_username }}
  DOCKER_PASSWORD: ${{ secrets.docker_password }}

jobs:

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout develop branch
  #       uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false

  #     - name: Run Node.js test
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #         scope: "@ndcmsl"
  #         registry-url: "https://npm.pkg.github.com"
  #     - run: npm install
  #     - run: npm run test
  
  build:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.token }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}