name: PR Merge & Build Check

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      is-microservice:
        required: false
        default: false
        type: boolean
env:
  RELEASE_BOT_APP_ID: 4176453
  IS_MICROSERVICE: ${{ inputs.is-microservice }}

permissions:
  contents: read
  packages: read

jobs:
  validate-merge-and-build:
    name: Merge PR with main & compile
    runs-on: self-hosted

    steps:
      - name: Generate release bot token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.token }}
          owner: ${{ github.repository_owner }}

      - name: Export release bot token
        run: |
          echo "GH_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"
          echo "NPM_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"
          echo "NODE_AUTH_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"

      - name: Checkout PR code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Necesario para hacer merge con otra rama

      - name: Install dependencies
        run: npm ci

      - name: Fetch target branch (main)
        run: git fetch origin main

      - name: Merge PR with main (test merge)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge origin/main --no-edit

      - name: Build after merge
        run: npm run build
