name: Release dotnet
on:
  workflow_call:
    secrets:
      token:
        required: true
      cliq_webhook:
        required: true
      cliq_token:
        required: true    
env:
  GH_TOKEN: ${{ secrets.token }}
  NPM_TOKEN: ${{ secrets.token }}
  NODE_AUTH_TOKEN: ${{ secrets.token }}
jobs:
  release:
    if: "!contains(github.event.commits[0].message, 'Initial commit')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set repository name
        run: echo REPO_NAME=$(echo ${{ github.repository }} | cut -d "/" -f 2) >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install semantic-release
        run: npm install 
      - name: Release
        run: npx semantic-release
      - name: Second Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Send Cliq release microservice
        uses: ndcmsl/cliq-sender-action@main
        with:
          webhook: ${{ secrets.cliq_webhook }}
          token: ${{ secrets.cliq_token }}
          title: ${{ env.REPO_NAME }}
          sender-name: Github Actions
          sender-image: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          tag: true