
name: Release dotnet
on:
  workflow_call:
    secrets:
      token:
        required: true
env:
  GH_TOKEN: ${{ secrets.token }}
  NPM_TOKEN: ${{ secrets.token }}
  NODE_AUTH_TOKEN: ${{ secrets.token }}
jobs:
  release:
    name: Release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set repository name
        run: echo REPO_NAME=$(echo ${{ github.repository }} | cut -d "/" -f 2) >> $GITHUB_ENV
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.6.1'
      #     scope: "@ndcmsl"
      #     registry-url: "https://npm.pkg.github.com"
      #     cache: 'npm'
      # - name: Install npm v9.6.4 
      #   run: npm install -g npm@v9.6.4
      # - name: Stop service
      #   run: sudo systemctl stop dotnet-erp.service || true
      - name: Setup .NET 6.x
        run: dotnet publish /deployment/dotnet-erp.logistic_test/project/dotnet-erp.logistic_test/Erp.Logistic/Erp.Logistic.csproj -c Release -o /deployment/dotnet-erp.logistic_test/dist -r linux-x64 --self-contained false
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_BEAST }}
      - name: PM2 SSH COMMANDS
        run: |
          ssh -o StrictHostKeyChecking=no user@10.3.200.156 "pm2 flush Dotnet-Erp.Logistic_test || true"
          ssh -o StrictHostKeyChecking=no user@10.3.200.156 "pm2 reload /deployment/dotnet-erp.logistic_test/ecosystem.config.js --time && pm2 reset all || true"
      # - name: start service
      #   run: sudo systemctl start dotnet-erp.service
      # - name: Start 
      #   run: cd /deployment/dotnet-erp.logistic/YourBlazorApp/ && dotnet Erp.Logistic.dll 
